# site settings
title: Fundación
subtitle:  SAN VICENTE PALLOTTI
email: fundacionsanvicentepallotti52@gmail.com
description: Fundación San vicente pallotti es na institución de ayuda para la comunidad mas necesitada, donde se imparte el amor al rojimo con moral cristiana y católca
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: Avenida. Las Aves con Av. Los Roques, Casa Iglesia Asunción de María, Urb Las Islas (Villa Panamericana). Guarenas, Edo. Miranda.
city: GUARENAS
state: Miranda
zip_code: 1220
country: Venezuela
phone: (+58) 412 905 98 17

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://fundacionsanvicentepallotti.github.io/
  GitLab:
  Google-Plus: 
  Instagram: https://www.instagram.com/fundacionsanvicentepallotti/?hl=es
  LinkedIn: 
  Twitter: https://x.com/FSPallottivzla
  Facebook: https://www.facebook.com/p/Fundacion-San-Vicente-Pallotti-vzla-100069215535439/?paipv=0&eav=AfZd5VC0PCFlxPg2_3BOZHpJiG3hrKkOm8FGDtV4AqnoTGHPLiP0Q5jHDxnfbSNGDps&_rdr
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
